# site settings
title: Jeroen van de Ven;
subtitle: Software Engineer
email: jeroen [at] <this domain>
description: I'm an experienced, passionate software engineer with a feel for entrepreneurship
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://jeroenvandeven.nl # the base hostname & protocol for your site
author: Jeroen van de Ven
# street_address: 1234 Somewhere Road
city: Eindhoven
#state: TN
#zip_code: 55555
country: The Netherlands
phone: Upon request

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/JeroenvdV
  GitLab:
  # Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/jeroenvandevennl
  # Twitter: https://twitter.com/jeroen_vandeven
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
